---
title: "Autoencoder Example"
author: "Saul Lugo"
date: "17/11/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r starting_h2o}
library(h2o)
myh2o <- h2o.init(nthreads = -1)
h2o.removeAll()
```

```{r}
mydata <- read.csv("data/mnist.csv")

#EXAMINAR LOS DATOS EN ENVIRONMENT #####################################

par(mfrow = c(10,10), mai=c(0,0,0,0))

for(i in 1:100){
  y = as.matrix(mydata[i, 2:785])
  dim(y) = c(28,28)
  image(y[,nrow(y):1], axes = FALSE, col = gray(255:0 / 255))
  text(0.2, 0, mydata[i,1], cex = 3, col = 2, pos = c(3,4))
}
```

```{r}
plotDigit <- function(mydata, rec_error) {
    len <- nrow(mydata)
    N <- ceiling(sqrt(len))
    par(mfrow=c(N,N),pty='s',mar=c(1,1,1,1),xaxt='n',yaxt='n')
    for (i in 1:nrow(mydata)) {
      colors<-c('white','black')
      cus_col<-colorRampPalette(colors=colors)
      z<-array(mydata[i,],dim=c(28,28))
      z<-z[,28:1]
      image(1:28,1:28,z,main=paste0("rec_error: ", round(rec_error[i],4)),col=cus_col(256))
    }
  }
  plotDigits <- function(data, rec_error, rows) {
    row_idx <- sort(order(rec_error[,1],decreasing=F)[rows])
    my_rec_error <- rec_error[row_idx,]
    my_data <- as.matrix(as.data.frame(data[row_idx,]))
    plotDigit(my_data, my_rec_error)
  }
```


```{r h2o_model}
library(caret)

inTrain <- createDataPartition(y=mydata$label, p = 0.1, list = FALSE)
train <- mydata[inTrain,]
test <- mydata[-inTrain,]

train.hex <- as.h2o(train)

autoe.model <- h2o.deeplearning(
  x = 2:785,
  training_frame = train.hex,
  hidden = c(400,200,3,200,400),
  epochs = 1,
  activation = "Tanh",
  autoencoder = TRUE,
  stopping_rounds = 0,
  model_id = "autoe_400_200_3_100e"
)

```

```{r extra_features}
library(ggplot2)
library(scatterplot3d)

par(mfrow = c(1,1), mai=c(0,0,0,0))

my2features <- h2o.deepfeatures(autoe.model, train.hex, layer = 3)

plotdata2 <- as.data.frame(my2features)
plotdata2$label <- as.character(as.vector(train.hex[,1]))
head(plotdata2)

Cols <- function(vec){
  cols <- rainbow(length(unique(vec)))
  return(cols[as.numeric(as.factor(vec))])
}

scatterplot3d(plotdata2$DF.L3.C1,plotdata2$DF.L3.C2,plotdata2$DF.L3.C3,color=Cols(plotdata2$label),main="Visualización 3D")

```


#Reconstrucción de los datos - Utilizando el Decoder

```{r}
#Ahora entrenemos otro AE con más neuronas en la capa oculta para poder reconstruir los datos originales.
autoe.model2 <- h2o.deeplearning(
  x = 2:785,
  training_frame = train.hex,
  activation="Tanh",
  autoencoder=T,
  hidden=c(50),
  l1=1e-5,
  ignore_const_cols=F,
  epochs=1,
  model_id = "autoe_50"
)

test.hex <- as.h2o(test[1:100,])
test_rec_error <- as.data.frame(h2o.anomaly(autoe.model2,test.hex))

test_recon <- predict(autoe.model2,test.hex)

##Reconstrucciones con el menor error de reconstrucción

plotDigits(test_recon,test_rec_error,c(1:25))

```

```{r}
##Reconstrucciones con un error medio de reconstrucción

plotDigits(test_recon,test_rec_error,c(50:75))


```

```{r}
##Reconstrucciones con el peor error de reconstrucción

plotDigits(test_recon,test_rec_error,c(75:100))

```
